# .gitlab-ci.yml

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: 'your-docker-registry' # Replace with your registry
  APP_NAME: 'doc-nest'
  IMAGE_TAG: '$CI_COMMIT_SHA' # Use commit SHA for unique tags
  SERVER_IP: 'your-server-ip'
  SERVER_USER: 'your-server-user'
  DEPLOY_DIR: '/path/to/deploy/directory'
  PORT: 'your-app-port'
  # Environment variables (Use GitLab CI/CD variables for sensitive data)
  NODE_ENV: 'production'
  PG_HOST: '$PG_HOST'
  PG_DATABASE: '$PG_DATABASE'
  PG_USER: '$PG_USER'
  PG_PASSWORD: '$PG_PASSWORD'
  PG_PORT: '$PG_PORT'
  JWT_SECRET: '$JWT_SECRET'
  JWT_EXPIRES_IN: '$JWT_EXPIRES_IN'
  AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
  AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
  AWS_REGION: '$AWS_REGION'
  AWS_BUCKET_NAME: '$AWS_BUCKET_NAME'
  INGESTION_SERVICE_URL: '$INGESTION_SERVICE_URL'

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$APP_NAME:$IMAGE_TAG" .
    - docker tag "$APP_NAME:$IMAGE_TAG" "$DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG"
    - docker push "$DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG"

deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client
  script:
    - ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" "$SERVER_USER@$SERVER_IP" << EOF
      echo "Deploying $APP_NAME..."
      mkdir -p "$DEPLOY_DIR"
      docker stop "$APP_NAME" || true
      docker rm "$APP_NAME" || true
      docker pull "$DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG"
      docker run -d \
      --name "$APP_NAME" \
      -p "$PORT:$PORT" \
      -e NODE_ENV="$NODE_ENV" \
      -e PORT="$PORT" \
      -e PG_HOST="$PG_HOST" \
      -e PG_DATABASE="$PG_DATABASE" \
      -e PG_USER="$PG_USER" \
      -e PG_PASSWORD="$PG_PASSWORD" \
      -e PG_PORT="$PG_PORT" \
      -e JWT_SECRET="$JWT_SECRET" \
      -e JWT_EXPIRES_IN="$JWT_EXPIRES_IN" \
      -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
      -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
      -e AWS_REGION="$AWS_REGION" \
      -e AWS_BUCKET_NAME="$AWS_BUCKET_NAME" \
      -e INGESTION_SERVICE_URL="$INGESTION_SERVICE_URL" \
      "$DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG"
      echo "Deployment of $APP_NAME complete."
      EOF
  environment:
    name: production
  only:
    - main # Or your production branch name
